version: "3"
services:
  server:
    image: jetbrains/teamcity-server:2017.2.4
    ports:
      - "8112:8111"
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./log_dir:/opt/teamcity/logs
  teamcity-agent:
    image: jetbrains/teamcity-agent:2017.2.4
    environment:
      - SERVER_URL=http://server:8111
      - AGENT_NAME=regular_agent